// File generated by FlutterFire CLI & configured for AgriSync Cloud Services (CPMK 5)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZYpSr8IISTSreunOFD_ML0BKXwKqcSQ',
    appId: '1:239266668956:android:c3068cfea3f1839e0e2859',
    messagingSenderId: '239266668956',
    projectId: 'agrisync-50dc0',
    authDomain: 'agrisync-50dc0.firebaseapp.com',
    storageBucket: 'agrisync-50dc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZYpSr8IISTSreunOFD_ML0BKXwKqcSQ',
    appId: '1:239266668956:android:c3068cfea3f1839e0e2859',
    messagingSenderId: '239266668956',
    projectId: 'agrisync-50dc0',
    storageBucket: 'agrisync-50dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtZYpSr8IISTSreunOFD_ML0BKXwKqcSQ',
    appId: '1:239266668956:ios:ebafa2uilbsng5debnglmdgv399dgbm6',
    messagingSenderId: '239266668956',
    projectId: 'agrisync-50dc0',
    storageBucket: 'agrisync-50dc0.firebasestorage.app',
    iosBundleId: 'com.agrisync.agrisync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtZYpSr8IISTSreunOFD_ML0BKXwKqcSQ',
    appId: '1:239266668956:ios:ebafa2uilbsng5debnglmdgv399dgbm6',
    messagingSenderId: '239266668956',
    projectId: 'agrisync-50dc0',
    storageBucket: 'agrisync-50dc0.firebasestorage.app',
    iosBundleId: 'com.agrisync.agrisync',
  );
}
